package com.cafucaa.alumniassociation.model;

import java.util.Date;

public class CaActivity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_activity.CA_Activity_ID
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    private Integer caActivityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_activity.activity_class
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    private String activityClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_activity.activity_back_or_not
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    private Boolean activityBackOrNot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_activity.activity_creater
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    private String activityCreater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_activity.activity_date
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    private Date activityDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_activity.activity_site
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    private String activitySite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_activity.activity_status
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    private Integer activityStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_activity.activity_result
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    private Boolean activityResult;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_activity.CA_Activity_ID
     *
     * @return the value of ca_activity.CA_Activity_ID
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public Integer getCaActivityId() {
        return caActivityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_activity.CA_Activity_ID
     *
     * @param caActivityId the value for ca_activity.CA_Activity_ID
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public void setCaActivityId(Integer caActivityId) {
        this.caActivityId = caActivityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_activity.activity_class
     *
     * @return the value of ca_activity.activity_class
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public String getActivityClass() {
        return activityClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_activity.activity_class
     *
     * @param activityClass the value for ca_activity.activity_class
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public void setActivityClass(String activityClass) {
        this.activityClass = activityClass == null ? null : activityClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_activity.activity_back_or_not
     *
     * @return the value of ca_activity.activity_back_or_not
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public Boolean getActivityBackOrNot() {
        return activityBackOrNot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_activity.activity_back_or_not
     *
     * @param activityBackOrNot the value for ca_activity.activity_back_or_not
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public void setActivityBackOrNot(Boolean activityBackOrNot) {
        this.activityBackOrNot = activityBackOrNot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_activity.activity_creater
     *
     * @return the value of ca_activity.activity_creater
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public String getActivityCreater() {
        return activityCreater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_activity.activity_creater
     *
     * @param activityCreater the value for ca_activity.activity_creater
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public void setActivityCreater(String activityCreater) {
        this.activityCreater = activityCreater == null ? null : activityCreater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_activity.activity_date
     *
     * @return the value of ca_activity.activity_date
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public Date getActivityDate() {
        return activityDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_activity.activity_date
     *
     * @param activityDate the value for ca_activity.activity_date
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public void setActivityDate(Date activityDate) {
        this.activityDate = activityDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_activity.activity_site
     *
     * @return the value of ca_activity.activity_site
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public String getActivitySite() {
        return activitySite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_activity.activity_site
     *
     * @param activitySite the value for ca_activity.activity_site
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public void setActivitySite(String activitySite) {
        this.activitySite = activitySite == null ? null : activitySite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_activity.activity_status
     *
     * @return the value of ca_activity.activity_status
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public Integer getActivityStatus() {
        return activityStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_activity.activity_status
     *
     * @param activityStatus the value for ca_activity.activity_status
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public void setActivityStatus(Integer activityStatus) {
        this.activityStatus = activityStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_activity.activity_result
     *
     * @return the value of ca_activity.activity_result
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public Boolean getActivityResult() {
        return activityResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_activity.activity_result
     *
     * @param activityResult the value for ca_activity.activity_result
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public void setActivityResult(Boolean activityResult) {
        this.activityResult = activityResult;
    }
}