package com.cafucaa.alumniassociation.model;

public class CaActivityWithBLOBs extends CaActivity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_activity.activity_content
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    private String activityContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_activity.activity_illustration
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    private String activityIllustration;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_activity.activity_content
     *
     * @return the value of ca_activity.activity_content
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public String getActivityContent() {
        return activityContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_activity.activity_content
     *
     * @param activityContent the value for ca_activity.activity_content
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public void setActivityContent(String activityContent) {
        this.activityContent = activityContent == null ? null : activityContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_activity.activity_illustration
     *
     * @return the value of ca_activity.activity_illustration
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public String getActivityIllustration() {
        return activityIllustration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_activity.activity_illustration
     *
     * @param activityIllustration the value for ca_activity.activity_illustration
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public void setActivityIllustration(String activityIllustration) {
        this.activityIllustration = activityIllustration == null ? null : activityIllustration.trim();
    }
}