package com.cafucaa.alumniassociation.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class CaAlumniExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ca_alumni
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ca_alumni
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ca_alumni
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_alumni
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public CaAlumniExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_alumni
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_alumni
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_alumni
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_alumni
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_alumni
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_alumni
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_alumni
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_alumni
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_alumni
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_alumni
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ca_alumni
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andCaAlumniIdIsNull() {
            addCriterion("CA_Alumni_ID is null");
            return (Criteria) this;
        }

        public Criteria andCaAlumniIdIsNotNull() {
            addCriterion("CA_Alumni_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCaAlumniIdEqualTo(Integer value) {
            addCriterion("CA_Alumni_ID =", value, "caAlumniId");
            return (Criteria) this;
        }

        public Criteria andCaAlumniIdNotEqualTo(Integer value) {
            addCriterion("CA_Alumni_ID <>", value, "caAlumniId");
            return (Criteria) this;
        }

        public Criteria andCaAlumniIdGreaterThan(Integer value) {
            addCriterion("CA_Alumni_ID >", value, "caAlumniId");
            return (Criteria) this;
        }

        public Criteria andCaAlumniIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("CA_Alumni_ID >=", value, "caAlumniId");
            return (Criteria) this;
        }

        public Criteria andCaAlumniIdLessThan(Integer value) {
            addCriterion("CA_Alumni_ID <", value, "caAlumniId");
            return (Criteria) this;
        }

        public Criteria andCaAlumniIdLessThanOrEqualTo(Integer value) {
            addCriterion("CA_Alumni_ID <=", value, "caAlumniId");
            return (Criteria) this;
        }

        public Criteria andCaAlumniIdIn(List<Integer> values) {
            addCriterion("CA_Alumni_ID in", values, "caAlumniId");
            return (Criteria) this;
        }

        public Criteria andCaAlumniIdNotIn(List<Integer> values) {
            addCriterion("CA_Alumni_ID not in", values, "caAlumniId");
            return (Criteria) this;
        }

        public Criteria andCaAlumniIdBetween(Integer value1, Integer value2) {
            addCriterion("CA_Alumni_ID between", value1, value2, "caAlumniId");
            return (Criteria) this;
        }

        public Criteria andCaAlumniIdNotBetween(Integer value1, Integer value2) {
            addCriterion("CA_Alumni_ID not between", value1, value2, "caAlumniId");
            return (Criteria) this;
        }

        public Criteria andCaRoleIdIsNull() {
            addCriterion("CA_Role_ID is null");
            return (Criteria) this;
        }

        public Criteria andCaRoleIdIsNotNull() {
            addCriterion("CA_Role_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCaRoleIdEqualTo(Integer value) {
            addCriterion("CA_Role_ID =", value, "caRoleId");
            return (Criteria) this;
        }

        public Criteria andCaRoleIdNotEqualTo(Integer value) {
            addCriterion("CA_Role_ID <>", value, "caRoleId");
            return (Criteria) this;
        }

        public Criteria andCaRoleIdGreaterThan(Integer value) {
            addCriterion("CA_Role_ID >", value, "caRoleId");
            return (Criteria) this;
        }

        public Criteria andCaRoleIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("CA_Role_ID >=", value, "caRoleId");
            return (Criteria) this;
        }

        public Criteria andCaRoleIdLessThan(Integer value) {
            addCriterion("CA_Role_ID <", value, "caRoleId");
            return (Criteria) this;
        }

        public Criteria andCaRoleIdLessThanOrEqualTo(Integer value) {
            addCriterion("CA_Role_ID <=", value, "caRoleId");
            return (Criteria) this;
        }

        public Criteria andCaRoleIdIn(List<Integer> values) {
            addCriterion("CA_Role_ID in", values, "caRoleId");
            return (Criteria) this;
        }

        public Criteria andCaRoleIdNotIn(List<Integer> values) {
            addCriterion("CA_Role_ID not in", values, "caRoleId");
            return (Criteria) this;
        }

        public Criteria andCaRoleIdBetween(Integer value1, Integer value2) {
            addCriterion("CA_Role_ID between", value1, value2, "caRoleId");
            return (Criteria) this;
        }

        public Criteria andCaRoleIdNotBetween(Integer value1, Integer value2) {
            addCriterion("CA_Role_ID not between", value1, value2, "caRoleId");
            return (Criteria) this;
        }

        public Criteria andCaClassIdIsNull() {
            addCriterion("CA_Class_ID is null");
            return (Criteria) this;
        }

        public Criteria andCaClassIdIsNotNull() {
            addCriterion("CA_Class_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCaClassIdEqualTo(Integer value) {
            addCriterion("CA_Class_ID =", value, "caClassId");
            return (Criteria) this;
        }

        public Criteria andCaClassIdNotEqualTo(Integer value) {
            addCriterion("CA_Class_ID <>", value, "caClassId");
            return (Criteria) this;
        }

        public Criteria andCaClassIdGreaterThan(Integer value) {
            addCriterion("CA_Class_ID >", value, "caClassId");
            return (Criteria) this;
        }

        public Criteria andCaClassIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("CA_Class_ID >=", value, "caClassId");
            return (Criteria) this;
        }

        public Criteria andCaClassIdLessThan(Integer value) {
            addCriterion("CA_Class_ID <", value, "caClassId");
            return (Criteria) this;
        }

        public Criteria andCaClassIdLessThanOrEqualTo(Integer value) {
            addCriterion("CA_Class_ID <=", value, "caClassId");
            return (Criteria) this;
        }

        public Criteria andCaClassIdIn(List<Integer> values) {
            addCriterion("CA_Class_ID in", values, "caClassId");
            return (Criteria) this;
        }

        public Criteria andCaClassIdNotIn(List<Integer> values) {
            addCriterion("CA_Class_ID not in", values, "caClassId");
            return (Criteria) this;
        }

        public Criteria andCaClassIdBetween(Integer value1, Integer value2) {
            addCriterion("CA_Class_ID between", value1, value2, "caClassId");
            return (Criteria) this;
        }

        public Criteria andCaClassIdNotBetween(Integer value1, Integer value2) {
            addCriterion("CA_Class_ID not between", value1, value2, "caClassId");
            return (Criteria) this;
        }

        public Criteria andAlumniNameIsNull() {
            addCriterion("alumni_name is null");
            return (Criteria) this;
        }

        public Criteria andAlumniNameIsNotNull() {
            addCriterion("alumni_name is not null");
            return (Criteria) this;
        }

        public Criteria andAlumniNameEqualTo(String value) {
            addCriterion("alumni_name =", value, "alumniName");
            return (Criteria) this;
        }

        public Criteria andAlumniNameNotEqualTo(String value) {
            addCriterion("alumni_name <>", value, "alumniName");
            return (Criteria) this;
        }

        public Criteria andAlumniNameGreaterThan(String value) {
            addCriterion("alumni_name >", value, "alumniName");
            return (Criteria) this;
        }

        public Criteria andAlumniNameGreaterThanOrEqualTo(String value) {
            addCriterion("alumni_name >=", value, "alumniName");
            return (Criteria) this;
        }

        public Criteria andAlumniNameLessThan(String value) {
            addCriterion("alumni_name <", value, "alumniName");
            return (Criteria) this;
        }

        public Criteria andAlumniNameLessThanOrEqualTo(String value) {
            addCriterion("alumni_name <=", value, "alumniName");
            return (Criteria) this;
        }

        public Criteria andAlumniNameLike(String value) {
            addCriterion("alumni_name like", value, "alumniName");
            return (Criteria) this;
        }

        public Criteria andAlumniNameNotLike(String value) {
            addCriterion("alumni_name not like", value, "alumniName");
            return (Criteria) this;
        }

        public Criteria andAlumniNameIn(List<String> values) {
            addCriterion("alumni_name in", values, "alumniName");
            return (Criteria) this;
        }

        public Criteria andAlumniNameNotIn(List<String> values) {
            addCriterion("alumni_name not in", values, "alumniName");
            return (Criteria) this;
        }

        public Criteria andAlumniNameBetween(String value1, String value2) {
            addCriterion("alumni_name between", value1, value2, "alumniName");
            return (Criteria) this;
        }

        public Criteria andAlumniNameNotBetween(String value1, String value2) {
            addCriterion("alumni_name not between", value1, value2, "alumniName");
            return (Criteria) this;
        }

        public Criteria andAlumniStuNumberIsNull() {
            addCriterion("alumni_stu_number is null");
            return (Criteria) this;
        }

        public Criteria andAlumniStuNumberIsNotNull() {
            addCriterion("alumni_stu_number is not null");
            return (Criteria) this;
        }

        public Criteria andAlumniStuNumberEqualTo(String value) {
            addCriterion("alumni_stu_number =", value, "alumniStuNumber");
            return (Criteria) this;
        }

        public Criteria andAlumniStuNumberNotEqualTo(String value) {
            addCriterion("alumni_stu_number <>", value, "alumniStuNumber");
            return (Criteria) this;
        }

        public Criteria andAlumniStuNumberGreaterThan(String value) {
            addCriterion("alumni_stu_number >", value, "alumniStuNumber");
            return (Criteria) this;
        }

        public Criteria andAlumniStuNumberGreaterThanOrEqualTo(String value) {
            addCriterion("alumni_stu_number >=", value, "alumniStuNumber");
            return (Criteria) this;
        }

        public Criteria andAlumniStuNumberLessThan(String value) {
            addCriterion("alumni_stu_number <", value, "alumniStuNumber");
            return (Criteria) this;
        }

        public Criteria andAlumniStuNumberLessThanOrEqualTo(String value) {
            addCriterion("alumni_stu_number <=", value, "alumniStuNumber");
            return (Criteria) this;
        }

        public Criteria andAlumniStuNumberLike(String value) {
            addCriterion("alumni_stu_number like", value, "alumniStuNumber");
            return (Criteria) this;
        }

        public Criteria andAlumniStuNumberNotLike(String value) {
            addCriterion("alumni_stu_number not like", value, "alumniStuNumber");
            return (Criteria) this;
        }

        public Criteria andAlumniStuNumberIn(List<String> values) {
            addCriterion("alumni_stu_number in", values, "alumniStuNumber");
            return (Criteria) this;
        }

        public Criteria andAlumniStuNumberNotIn(List<String> values) {
            addCriterion("alumni_stu_number not in", values, "alumniStuNumber");
            return (Criteria) this;
        }

        public Criteria andAlumniStuNumberBetween(String value1, String value2) {
            addCriterion("alumni_stu_number between", value1, value2, "alumniStuNumber");
            return (Criteria) this;
        }

        public Criteria andAlumniStuNumberNotBetween(String value1, String value2) {
            addCriterion("alumni_stu_number not between", value1, value2, "alumniStuNumber");
            return (Criteria) this;
        }

        public Criteria andAlumniSexIsNull() {
            addCriterion("alumni_sex is null");
            return (Criteria) this;
        }

        public Criteria andAlumniSexIsNotNull() {
            addCriterion("alumni_sex is not null");
            return (Criteria) this;
        }

        public Criteria andAlumniSexEqualTo(Boolean value) {
            addCriterion("alumni_sex =", value, "alumniSex");
            return (Criteria) this;
        }

        public Criteria andAlumniSexNotEqualTo(Boolean value) {
            addCriterion("alumni_sex <>", value, "alumniSex");
            return (Criteria) this;
        }

        public Criteria andAlumniSexGreaterThan(Boolean value) {
            addCriterion("alumni_sex >", value, "alumniSex");
            return (Criteria) this;
        }

        public Criteria andAlumniSexGreaterThanOrEqualTo(Boolean value) {
            addCriterion("alumni_sex >=", value, "alumniSex");
            return (Criteria) this;
        }

        public Criteria andAlumniSexLessThan(Boolean value) {
            addCriterion("alumni_sex <", value, "alumniSex");
            return (Criteria) this;
        }

        public Criteria andAlumniSexLessThanOrEqualTo(Boolean value) {
            addCriterion("alumni_sex <=", value, "alumniSex");
            return (Criteria) this;
        }

        public Criteria andAlumniSexIn(List<Boolean> values) {
            addCriterion("alumni_sex in", values, "alumniSex");
            return (Criteria) this;
        }

        public Criteria andAlumniSexNotIn(List<Boolean> values) {
            addCriterion("alumni_sex not in", values, "alumniSex");
            return (Criteria) this;
        }

        public Criteria andAlumniSexBetween(Boolean value1, Boolean value2) {
            addCriterion("alumni_sex between", value1, value2, "alumniSex");
            return (Criteria) this;
        }

        public Criteria andAlumniSexNotBetween(Boolean value1, Boolean value2) {
            addCriterion("alumni_sex not between", value1, value2, "alumniSex");
            return (Criteria) this;
        }

        public Criteria andAlumniSecondCollegeIsNull() {
            addCriterion("alumni_second_college is null");
            return (Criteria) this;
        }

        public Criteria andAlumniSecondCollegeIsNotNull() {
            addCriterion("alumni_second_college is not null");
            return (Criteria) this;
        }

        public Criteria andAlumniSecondCollegeEqualTo(String value) {
            addCriterion("alumni_second_college =", value, "alumniSecondCollege");
            return (Criteria) this;
        }

        public Criteria andAlumniSecondCollegeNotEqualTo(String value) {
            addCriterion("alumni_second_college <>", value, "alumniSecondCollege");
            return (Criteria) this;
        }

        public Criteria andAlumniSecondCollegeGreaterThan(String value) {
            addCriterion("alumni_second_college >", value, "alumniSecondCollege");
            return (Criteria) this;
        }

        public Criteria andAlumniSecondCollegeGreaterThanOrEqualTo(String value) {
            addCriterion("alumni_second_college >=", value, "alumniSecondCollege");
            return (Criteria) this;
        }

        public Criteria andAlumniSecondCollegeLessThan(String value) {
            addCriterion("alumni_second_college <", value, "alumniSecondCollege");
            return (Criteria) this;
        }

        public Criteria andAlumniSecondCollegeLessThanOrEqualTo(String value) {
            addCriterion("alumni_second_college <=", value, "alumniSecondCollege");
            return (Criteria) this;
        }

        public Criteria andAlumniSecondCollegeLike(String value) {
            addCriterion("alumni_second_college like", value, "alumniSecondCollege");
            return (Criteria) this;
        }

        public Criteria andAlumniSecondCollegeNotLike(String value) {
            addCriterion("alumni_second_college not like", value, "alumniSecondCollege");
            return (Criteria) this;
        }

        public Criteria andAlumniSecondCollegeIn(List<String> values) {
            addCriterion("alumni_second_college in", values, "alumniSecondCollege");
            return (Criteria) this;
        }

        public Criteria andAlumniSecondCollegeNotIn(List<String> values) {
            addCriterion("alumni_second_college not in", values, "alumniSecondCollege");
            return (Criteria) this;
        }

        public Criteria andAlumniSecondCollegeBetween(String value1, String value2) {
            addCriterion("alumni_second_college between", value1, value2, "alumniSecondCollege");
            return (Criteria) this;
        }

        public Criteria andAlumniSecondCollegeNotBetween(String value1, String value2) {
            addCriterion("alumni_second_college not between", value1, value2, "alumniSecondCollege");
            return (Criteria) this;
        }

        public Criteria andAlumniDateIsNull() {
            addCriterion("alumni_date is null");
            return (Criteria) this;
        }

        public Criteria andAlumniDateIsNotNull() {
            addCriterion("alumni_date is not null");
            return (Criteria) this;
        }

        public Criteria andAlumniDateEqualTo(Date value) {
            addCriterionForJDBCDate("alumni_date =", value, "alumniDate");
            return (Criteria) this;
        }

        public Criteria andAlumniDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("alumni_date <>", value, "alumniDate");
            return (Criteria) this;
        }

        public Criteria andAlumniDateGreaterThan(Date value) {
            addCriterionForJDBCDate("alumni_date >", value, "alumniDate");
            return (Criteria) this;
        }

        public Criteria andAlumniDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("alumni_date >=", value, "alumniDate");
            return (Criteria) this;
        }

        public Criteria andAlumniDateLessThan(Date value) {
            addCriterionForJDBCDate("alumni_date <", value, "alumniDate");
            return (Criteria) this;
        }

        public Criteria andAlumniDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("alumni_date <=", value, "alumniDate");
            return (Criteria) this;
        }

        public Criteria andAlumniDateIn(List<Date> values) {
            addCriterionForJDBCDate("alumni_date in", values, "alumniDate");
            return (Criteria) this;
        }

        public Criteria andAlumniDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("alumni_date not in", values, "alumniDate");
            return (Criteria) this;
        }

        public Criteria andAlumniDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("alumni_date between", value1, value2, "alumniDate");
            return (Criteria) this;
        }

        public Criteria andAlumniDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("alumni_date not between", value1, value2, "alumniDate");
            return (Criteria) this;
        }

        public Criteria andAlumniCareerIsNull() {
            addCriterion("alumni_career is null");
            return (Criteria) this;
        }

        public Criteria andAlumniCareerIsNotNull() {
            addCriterion("alumni_career is not null");
            return (Criteria) this;
        }

        public Criteria andAlumniCareerEqualTo(String value) {
            addCriterion("alumni_career =", value, "alumniCareer");
            return (Criteria) this;
        }

        public Criteria andAlumniCareerNotEqualTo(String value) {
            addCriterion("alumni_career <>", value, "alumniCareer");
            return (Criteria) this;
        }

        public Criteria andAlumniCareerGreaterThan(String value) {
            addCriterion("alumni_career >", value, "alumniCareer");
            return (Criteria) this;
        }

        public Criteria andAlumniCareerGreaterThanOrEqualTo(String value) {
            addCriterion("alumni_career >=", value, "alumniCareer");
            return (Criteria) this;
        }

        public Criteria andAlumniCareerLessThan(String value) {
            addCriterion("alumni_career <", value, "alumniCareer");
            return (Criteria) this;
        }

        public Criteria andAlumniCareerLessThanOrEqualTo(String value) {
            addCriterion("alumni_career <=", value, "alumniCareer");
            return (Criteria) this;
        }

        public Criteria andAlumniCareerLike(String value) {
            addCriterion("alumni_career like", value, "alumniCareer");
            return (Criteria) this;
        }

        public Criteria andAlumniCareerNotLike(String value) {
            addCriterion("alumni_career not like", value, "alumniCareer");
            return (Criteria) this;
        }

        public Criteria andAlumniCareerIn(List<String> values) {
            addCriterion("alumni_career in", values, "alumniCareer");
            return (Criteria) this;
        }

        public Criteria andAlumniCareerNotIn(List<String> values) {
            addCriterion("alumni_career not in", values, "alumniCareer");
            return (Criteria) this;
        }

        public Criteria andAlumniCareerBetween(String value1, String value2) {
            addCriterion("alumni_career between", value1, value2, "alumniCareer");
            return (Criteria) this;
        }

        public Criteria andAlumniCareerNotBetween(String value1, String value2) {
            addCriterion("alumni_career not between", value1, value2, "alumniCareer");
            return (Criteria) this;
        }

        public Criteria andAlumniCompanyIsNull() {
            addCriterion("alumni_company is null");
            return (Criteria) this;
        }

        public Criteria andAlumniCompanyIsNotNull() {
            addCriterion("alumni_company is not null");
            return (Criteria) this;
        }

        public Criteria andAlumniCompanyEqualTo(String value) {
            addCriterion("alumni_company =", value, "alumniCompany");
            return (Criteria) this;
        }

        public Criteria andAlumniCompanyNotEqualTo(String value) {
            addCriterion("alumni_company <>", value, "alumniCompany");
            return (Criteria) this;
        }

        public Criteria andAlumniCompanyGreaterThan(String value) {
            addCriterion("alumni_company >", value, "alumniCompany");
            return (Criteria) this;
        }

        public Criteria andAlumniCompanyGreaterThanOrEqualTo(String value) {
            addCriterion("alumni_company >=", value, "alumniCompany");
            return (Criteria) this;
        }

        public Criteria andAlumniCompanyLessThan(String value) {
            addCriterion("alumni_company <", value, "alumniCompany");
            return (Criteria) this;
        }

        public Criteria andAlumniCompanyLessThanOrEqualTo(String value) {
            addCriterion("alumni_company <=", value, "alumniCompany");
            return (Criteria) this;
        }

        public Criteria andAlumniCompanyLike(String value) {
            addCriterion("alumni_company like", value, "alumniCompany");
            return (Criteria) this;
        }

        public Criteria andAlumniCompanyNotLike(String value) {
            addCriterion("alumni_company not like", value, "alumniCompany");
            return (Criteria) this;
        }

        public Criteria andAlumniCompanyIn(List<String> values) {
            addCriterion("alumni_company in", values, "alumniCompany");
            return (Criteria) this;
        }

        public Criteria andAlumniCompanyNotIn(List<String> values) {
            addCriterion("alumni_company not in", values, "alumniCompany");
            return (Criteria) this;
        }

        public Criteria andAlumniCompanyBetween(String value1, String value2) {
            addCriterion("alumni_company between", value1, value2, "alumniCompany");
            return (Criteria) this;
        }

        public Criteria andAlumniCompanyNotBetween(String value1, String value2) {
            addCriterion("alumni_company not between", value1, value2, "alumniCompany");
            return (Criteria) this;
        }

        public Criteria andAlumniAddressIsNull() {
            addCriterion("alumni_address is null");
            return (Criteria) this;
        }

        public Criteria andAlumniAddressIsNotNull() {
            addCriterion("alumni_address is not null");
            return (Criteria) this;
        }

        public Criteria andAlumniAddressEqualTo(String value) {
            addCriterion("alumni_address =", value, "alumniAddress");
            return (Criteria) this;
        }

        public Criteria andAlumniAddressNotEqualTo(String value) {
            addCriterion("alumni_address <>", value, "alumniAddress");
            return (Criteria) this;
        }

        public Criteria andAlumniAddressGreaterThan(String value) {
            addCriterion("alumni_address >", value, "alumniAddress");
            return (Criteria) this;
        }

        public Criteria andAlumniAddressGreaterThanOrEqualTo(String value) {
            addCriterion("alumni_address >=", value, "alumniAddress");
            return (Criteria) this;
        }

        public Criteria andAlumniAddressLessThan(String value) {
            addCriterion("alumni_address <", value, "alumniAddress");
            return (Criteria) this;
        }

        public Criteria andAlumniAddressLessThanOrEqualTo(String value) {
            addCriterion("alumni_address <=", value, "alumniAddress");
            return (Criteria) this;
        }

        public Criteria andAlumniAddressLike(String value) {
            addCriterion("alumni_address like", value, "alumniAddress");
            return (Criteria) this;
        }

        public Criteria andAlumniAddressNotLike(String value) {
            addCriterion("alumni_address not like", value, "alumniAddress");
            return (Criteria) this;
        }

        public Criteria andAlumniAddressIn(List<String> values) {
            addCriterion("alumni_address in", values, "alumniAddress");
            return (Criteria) this;
        }

        public Criteria andAlumniAddressNotIn(List<String> values) {
            addCriterion("alumni_address not in", values, "alumniAddress");
            return (Criteria) this;
        }

        public Criteria andAlumniAddressBetween(String value1, String value2) {
            addCriterion("alumni_address between", value1, value2, "alumniAddress");
            return (Criteria) this;
        }

        public Criteria andAlumniAddressNotBetween(String value1, String value2) {
            addCriterion("alumni_address not between", value1, value2, "alumniAddress");
            return (Criteria) this;
        }

        public Criteria andAlumniAccountNumberIsNull() {
            addCriterion("alumni_account_number is null");
            return (Criteria) this;
        }

        public Criteria andAlumniAccountNumberIsNotNull() {
            addCriterion("alumni_account_number is not null");
            return (Criteria) this;
        }

        public Criteria andAlumniAccountNumberEqualTo(String value) {
            addCriterion("alumni_account_number =", value, "alumniAccountNumber");
            return (Criteria) this;
        }

        public Criteria andAlumniAccountNumberNotEqualTo(String value) {
            addCriterion("alumni_account_number <>", value, "alumniAccountNumber");
            return (Criteria) this;
        }

        public Criteria andAlumniAccountNumberGreaterThan(String value) {
            addCriterion("alumni_account_number >", value, "alumniAccountNumber");
            return (Criteria) this;
        }

        public Criteria andAlumniAccountNumberGreaterThanOrEqualTo(String value) {
            addCriterion("alumni_account_number >=", value, "alumniAccountNumber");
            return (Criteria) this;
        }

        public Criteria andAlumniAccountNumberLessThan(String value) {
            addCriterion("alumni_account_number <", value, "alumniAccountNumber");
            return (Criteria) this;
        }

        public Criteria andAlumniAccountNumberLessThanOrEqualTo(String value) {
            addCriterion("alumni_account_number <=", value, "alumniAccountNumber");
            return (Criteria) this;
        }

        public Criteria andAlumniAccountNumberLike(String value) {
            addCriterion("alumni_account_number like", value, "alumniAccountNumber");
            return (Criteria) this;
        }

        public Criteria andAlumniAccountNumberNotLike(String value) {
            addCriterion("alumni_account_number not like", value, "alumniAccountNumber");
            return (Criteria) this;
        }

        public Criteria andAlumniAccountNumberIn(List<String> values) {
            addCriterion("alumni_account_number in", values, "alumniAccountNumber");
            return (Criteria) this;
        }

        public Criteria andAlumniAccountNumberNotIn(List<String> values) {
            addCriterion("alumni_account_number not in", values, "alumniAccountNumber");
            return (Criteria) this;
        }

        public Criteria andAlumniAccountNumberBetween(String value1, String value2) {
            addCriterion("alumni_account_number between", value1, value2, "alumniAccountNumber");
            return (Criteria) this;
        }

        public Criteria andAlumniAccountNumberNotBetween(String value1, String value2) {
            addCriterion("alumni_account_number not between", value1, value2, "alumniAccountNumber");
            return (Criteria) this;
        }

        public Criteria andAlumniPasswordIsNull() {
            addCriterion("alumni_password is null");
            return (Criteria) this;
        }

        public Criteria andAlumniPasswordIsNotNull() {
            addCriterion("alumni_password is not null");
            return (Criteria) this;
        }

        public Criteria andAlumniPasswordEqualTo(String value) {
            addCriterion("alumni_password =", value, "alumniPassword");
            return (Criteria) this;
        }

        public Criteria andAlumniPasswordNotEqualTo(String value) {
            addCriterion("alumni_password <>", value, "alumniPassword");
            return (Criteria) this;
        }

        public Criteria andAlumniPasswordGreaterThan(String value) {
            addCriterion("alumni_password >", value, "alumniPassword");
            return (Criteria) this;
        }

        public Criteria andAlumniPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("alumni_password >=", value, "alumniPassword");
            return (Criteria) this;
        }

        public Criteria andAlumniPasswordLessThan(String value) {
            addCriterion("alumni_password <", value, "alumniPassword");
            return (Criteria) this;
        }

        public Criteria andAlumniPasswordLessThanOrEqualTo(String value) {
            addCriterion("alumni_password <=", value, "alumniPassword");
            return (Criteria) this;
        }

        public Criteria andAlumniPasswordLike(String value) {
            addCriterion("alumni_password like", value, "alumniPassword");
            return (Criteria) this;
        }

        public Criteria andAlumniPasswordNotLike(String value) {
            addCriterion("alumni_password not like", value, "alumniPassword");
            return (Criteria) this;
        }

        public Criteria andAlumniPasswordIn(List<String> values) {
            addCriterion("alumni_password in", values, "alumniPassword");
            return (Criteria) this;
        }

        public Criteria andAlumniPasswordNotIn(List<String> values) {
            addCriterion("alumni_password not in", values, "alumniPassword");
            return (Criteria) this;
        }

        public Criteria andAlumniPasswordBetween(String value1, String value2) {
            addCriterion("alumni_password between", value1, value2, "alumniPassword");
            return (Criteria) this;
        }

        public Criteria andAlumniPasswordNotBetween(String value1, String value2) {
            addCriterion("alumni_password not between", value1, value2, "alumniPassword");
            return (Criteria) this;
        }

        public Criteria andAluminCellphoneIsNull() {
            addCriterion("alumin_cellphone is null");
            return (Criteria) this;
        }

        public Criteria andAluminCellphoneIsNotNull() {
            addCriterion("alumin_cellphone is not null");
            return (Criteria) this;
        }

        public Criteria andAluminCellphoneEqualTo(String value) {
            addCriterion("alumin_cellphone =", value, "aluminCellphone");
            return (Criteria) this;
        }

        public Criteria andAluminCellphoneNotEqualTo(String value) {
            addCriterion("alumin_cellphone <>", value, "aluminCellphone");
            return (Criteria) this;
        }

        public Criteria andAluminCellphoneGreaterThan(String value) {
            addCriterion("alumin_cellphone >", value, "aluminCellphone");
            return (Criteria) this;
        }

        public Criteria andAluminCellphoneGreaterThanOrEqualTo(String value) {
            addCriterion("alumin_cellphone >=", value, "aluminCellphone");
            return (Criteria) this;
        }

        public Criteria andAluminCellphoneLessThan(String value) {
            addCriterion("alumin_cellphone <", value, "aluminCellphone");
            return (Criteria) this;
        }

        public Criteria andAluminCellphoneLessThanOrEqualTo(String value) {
            addCriterion("alumin_cellphone <=", value, "aluminCellphone");
            return (Criteria) this;
        }

        public Criteria andAluminCellphoneLike(String value) {
            addCriterion("alumin_cellphone like", value, "aluminCellphone");
            return (Criteria) this;
        }

        public Criteria andAluminCellphoneNotLike(String value) {
            addCriterion("alumin_cellphone not like", value, "aluminCellphone");
            return (Criteria) this;
        }

        public Criteria andAluminCellphoneIn(List<String> values) {
            addCriterion("alumin_cellphone in", values, "aluminCellphone");
            return (Criteria) this;
        }

        public Criteria andAluminCellphoneNotIn(List<String> values) {
            addCriterion("alumin_cellphone not in", values, "aluminCellphone");
            return (Criteria) this;
        }

        public Criteria andAluminCellphoneBetween(String value1, String value2) {
            addCriterion("alumin_cellphone between", value1, value2, "aluminCellphone");
            return (Criteria) this;
        }

        public Criteria andAluminCellphoneNotBetween(String value1, String value2) {
            addCriterion("alumin_cellphone not between", value1, value2, "aluminCellphone");
            return (Criteria) this;
        }

        public Criteria andAlumniEmailIsNull() {
            addCriterion("alumni_email is null");
            return (Criteria) this;
        }

        public Criteria andAlumniEmailIsNotNull() {
            addCriterion("alumni_email is not null");
            return (Criteria) this;
        }

        public Criteria andAlumniEmailEqualTo(String value) {
            addCriterion("alumni_email =", value, "alumniEmail");
            return (Criteria) this;
        }

        public Criteria andAlumniEmailNotEqualTo(String value) {
            addCriterion("alumni_email <>", value, "alumniEmail");
            return (Criteria) this;
        }

        public Criteria andAlumniEmailGreaterThan(String value) {
            addCriterion("alumni_email >", value, "alumniEmail");
            return (Criteria) this;
        }

        public Criteria andAlumniEmailGreaterThanOrEqualTo(String value) {
            addCriterion("alumni_email >=", value, "alumniEmail");
            return (Criteria) this;
        }

        public Criteria andAlumniEmailLessThan(String value) {
            addCriterion("alumni_email <", value, "alumniEmail");
            return (Criteria) this;
        }

        public Criteria andAlumniEmailLessThanOrEqualTo(String value) {
            addCriterion("alumni_email <=", value, "alumniEmail");
            return (Criteria) this;
        }

        public Criteria andAlumniEmailLike(String value) {
            addCriterion("alumni_email like", value, "alumniEmail");
            return (Criteria) this;
        }

        public Criteria andAlumniEmailNotLike(String value) {
            addCriterion("alumni_email not like", value, "alumniEmail");
            return (Criteria) this;
        }

        public Criteria andAlumniEmailIn(List<String> values) {
            addCriterion("alumni_email in", values, "alumniEmail");
            return (Criteria) this;
        }

        public Criteria andAlumniEmailNotIn(List<String> values) {
            addCriterion("alumni_email not in", values, "alumniEmail");
            return (Criteria) this;
        }

        public Criteria andAlumniEmailBetween(String value1, String value2) {
            addCriterion("alumni_email between", value1, value2, "alumniEmail");
            return (Criteria) this;
        }

        public Criteria andAlumniEmailNotBetween(String value1, String value2) {
            addCriterion("alumni_email not between", value1, value2, "alumniEmail");
            return (Criteria) this;
        }

        public Criteria andAlumniHotIsNull() {
            addCriterion("alumni_hot is null");
            return (Criteria) this;
        }

        public Criteria andAlumniHotIsNotNull() {
            addCriterion("alumni_hot is not null");
            return (Criteria) this;
        }

        public Criteria andAlumniHotEqualTo(Integer value) {
            addCriterion("alumni_hot =", value, "alumniHot");
            return (Criteria) this;
        }

        public Criteria andAlumniHotNotEqualTo(Integer value) {
            addCriterion("alumni_hot <>", value, "alumniHot");
            return (Criteria) this;
        }

        public Criteria andAlumniHotGreaterThan(Integer value) {
            addCriterion("alumni_hot >", value, "alumniHot");
            return (Criteria) this;
        }

        public Criteria andAlumniHotGreaterThanOrEqualTo(Integer value) {
            addCriterion("alumni_hot >=", value, "alumniHot");
            return (Criteria) this;
        }

        public Criteria andAlumniHotLessThan(Integer value) {
            addCriterion("alumni_hot <", value, "alumniHot");
            return (Criteria) this;
        }

        public Criteria andAlumniHotLessThanOrEqualTo(Integer value) {
            addCriterion("alumni_hot <=", value, "alumniHot");
            return (Criteria) this;
        }

        public Criteria andAlumniHotIn(List<Integer> values) {
            addCriterion("alumni_hot in", values, "alumniHot");
            return (Criteria) this;
        }

        public Criteria andAlumniHotNotIn(List<Integer> values) {
            addCriterion("alumni_hot not in", values, "alumniHot");
            return (Criteria) this;
        }

        public Criteria andAlumniHotBetween(Integer value1, Integer value2) {
            addCriterion("alumni_hot between", value1, value2, "alumniHot");
            return (Criteria) this;
        }

        public Criteria andAlumniHotNotBetween(Integer value1, Integer value2) {
            addCriterion("alumni_hot not between", value1, value2, "alumniHot");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ca_alumni
     *
     * @mbggenerated do_not_delete_during_merge Sat Jun 01 23:57:31 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ca_alumni
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}