package com.cafucaa.alumniassociation.model;

import java.util.Date;

public class CaAlumni {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_alumni.CA_Alumni_ID
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    private Integer caAlumniId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_alumni.CA_Role_ID
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    private Integer caRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_alumni.CA_Class_ID
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    private Integer caClassId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_alumni.alumni_name
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    private String alumniName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_alumni.alumni_stu_number
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    private String alumniStuNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_alumni.alumni_sex
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    private Boolean alumniSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_alumni.alumni_second_college
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    private String alumniSecondCollege;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_alumni.alumni_date
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    private Date alumniAdmissionDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_alumni.alumni_career
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    private String alumniCareer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_alumni.alumni_company
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    private String alumniCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_alumni.alumni_address
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    private String alumniAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_alumni.alumni_account_number
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    private String alumniAccountNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_alumni.alumni_password
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    private String alumniPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_alumni.alumin_cellphone
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    private String aluminCellphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_alumni.alumni_email
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    private String alumniEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_alumni.alumni_hot
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    private Integer alumniHot;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_alumni.CA_Alumni_ID
     *
     * @return the value of ca_alumni.CA_Alumni_ID
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public Integer getCaAlumniId() {
        return caAlumniId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_alumni.CA_Alumni_ID
     *
     * @param caAlumniId the value for ca_alumni.CA_Alumni_ID
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public void setCaAlumniId(Integer caAlumniId) {
        this.caAlumniId = caAlumniId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_alumni.CA_Role_ID
     *
     * @return the value of ca_alumni.CA_Role_ID
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public Integer getCaRoleId() {
        return caRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_alumni.CA_Role_ID
     *
     * @param caRoleId the value for ca_alumni.CA_Role_ID
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public void setCaRoleId(Integer caRoleId) {
        this.caRoleId = caRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_alumni.CA_Class_ID
     *
     * @return the value of ca_alumni.CA_Class_ID
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public Integer getCaClassId() {
        return caClassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_alumni.CA_Class_ID
     *
     * @param caClassId the value for ca_alumni.CA_Class_ID
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public void setCaClassId(Integer caClassId) {
        this.caClassId = caClassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_alumni.alumni_name
     *
     * @return the value of ca_alumni.alumni_name
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public String getAlumniName() {
        return alumniName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_alumni.alumni_name
     *
     * @param alumniName the value for ca_alumni.alumni_name
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public void setAlumniName(String alumniName) {
        this.alumniName = alumniName == null ? null : alumniName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_alumni.alumni_stu_number
     *
     * @return the value of ca_alumni.alumni_stu_number
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public String getAlumniStuNumber() {
        return alumniStuNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_alumni.alumni_stu_number
     *
     * @param alumniStuNumber the value for ca_alumni.alumni_stu_number
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public void setAlumniStuNumber(String alumniStuNumber) {
        this.alumniStuNumber = alumniStuNumber == null ? null : alumniStuNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_alumni.alumni_sex
     *
     * @return the value of ca_alumni.alumni_sex
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public Boolean getAlumniSex() {
        return alumniSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_alumni.alumni_sex
     *
     * @param alumniSex the value for ca_alumni.alumni_sex
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public void setAlumniSex(Boolean alumniSex) {
        this.alumniSex = alumniSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_alumni.alumni_second_college
     *
     * @return the value of ca_alumni.alumni_second_college
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public String getAlumniSecondCollege() {
        return alumniSecondCollege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_alumni.alumni_second_college
     *
     * @param alumniSecondCollege the value for ca_alumni.alumni_second_college
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public void setAlumniSecondCollege(String alumniSecondCollege) {
        this.alumniSecondCollege = alumniSecondCollege == null ? null : alumniSecondCollege.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_alumni.alumni_date
     *
     * @return the value of ca_alumni.alumni_date
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public Date getAlumniAdmissionDate() {
        return alumniAdmissionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_alumni.alumni_date
     *
     * @param alumniAdmissionDate the value for ca_alumni.alumni_date
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public void setAlumniAdmissionDate(Date alumniAdmissionDate) {
        this.alumniAdmissionDate = alumniAdmissionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_alumni.alumni_career
     *
     * @return the value of ca_alumni.alumni_career
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public String getAlumniCareer() {
        return alumniCareer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_alumni.alumni_career
     *
     * @param alumniCareer the value for ca_alumni.alumni_career
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public void setAlumniCareer(String alumniCareer) {
        this.alumniCareer = alumniCareer == null ? null : alumniCareer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_alumni.alumni_company
     *
     * @return the value of ca_alumni.alumni_company
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public String getAlumniCompany() {
        return alumniCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_alumni.alumni_company
     *
     * @param alumniCompany the value for ca_alumni.alumni_company
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public void setAlumniCompany(String alumniCompany) {
        this.alumniCompany = alumniCompany == null ? null : alumniCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_alumni.alumni_address
     *
     * @return the value of ca_alumni.alumni_address
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public String getAlumniAddress() {
        return alumniAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_alumni.alumni_address
     *
     * @param alumniAddress the value for ca_alumni.alumni_address
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public void setAlumniAddress(String alumniAddress) {
        this.alumniAddress = alumniAddress == null ? null : alumniAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_alumni.alumni_account_number
     *
     * @return the value of ca_alumni.alumni_account_number
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public String getAlumniAccountNumber() {
        return alumniAccountNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_alumni.alumni_account_number
     *
     * @param alumniAccountNumber the value for ca_alumni.alumni_account_number
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public void setAlumniAccountNumber(String alumniAccountNumber) {
        this.alumniAccountNumber = alumniAccountNumber == null ? null : alumniAccountNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_alumni.alumni_password
     *
     * @return the value of ca_alumni.alumni_password
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public String getAlumniPassword() {
        return alumniPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_alumni.alumni_password
     *
     * @param alumniPassword the value for ca_alumni.alumni_password
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public void setAlumniPassword(String alumniPassword) {
        this.alumniPassword = alumniPassword == null ? null : alumniPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_alumni.alumin_cellphone
     *
     * @return the value of ca_alumni.alumin_cellphone
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public String getAluminCellphone() {
        return aluminCellphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_alumni.alumin_cellphone
     *
     * @param aluminCellphone the value for ca_alumni.alumin_cellphone
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public void setAluminCellphone(String aluminCellphone) {
        this.aluminCellphone = aluminCellphone == null ? null : aluminCellphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_alumni.alumni_email
     *
     * @return the value of ca_alumni.alumni_email
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public String getAlumniEmail() {
        return alumniEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_alumni.alumni_email
     *
     * @param alumniEmail the value for ca_alumni.alumni_email
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public void setAlumniEmail(String alumniEmail) {
        this.alumniEmail = alumniEmail == null ? null : alumniEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_alumni.alumni_hot
     *
     * @return the value of ca_alumni.alumni_hot
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public Integer getAlumniHot() {
        return alumniHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_alumni.alumni_hot
     *
     * @param alumniHot the value for ca_alumni.alumni_hot
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public void setAlumniHot(Integer alumniHot) {
        this.alumniHot = alumniHot;
    }
}