package com.cafucaa.alumniassociation.model;

public class CaClass {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_class.CA_Class_ID
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    private Integer caClassId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_class.class_name
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_class.class_creater
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    private String classCreater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_class.class_quantity
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    private Integer classQuantity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_class.CA_Class_ID
     *
     * @return the value of ca_class.CA_Class_ID
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public Integer getCaClassId() {
        return caClassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_class.CA_Class_ID
     *
     * @param caClassId the value for ca_class.CA_Class_ID
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public void setCaClassId(Integer caClassId) {
        this.caClassId = caClassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_class.class_name
     *
     * @return the value of ca_class.class_name
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_class.class_name
     *
     * @param className the value for ca_class.class_name
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_class.class_creater
     *
     * @return the value of ca_class.class_creater
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public String getClassCreater() {
        return classCreater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_class.class_creater
     *
     * @param classCreater the value for ca_class.class_creater
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public void setClassCreater(String classCreater) {
        this.classCreater = classCreater == null ? null : classCreater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_class.class_quantity
     *
     * @return the value of ca_class.class_quantity
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public Integer getClassQuantity() {
        return classQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_class.class_quantity
     *
     * @param classQuantity the value for ca_class.class_quantity
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public void setClassQuantity(Integer classQuantity) {
        this.classQuantity = classQuantity;
    }
}