package com.cafucaa.alumniassociation.model;

public class CaPrivalege {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_privalege.CA_Privalege_ID
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    private Integer caPrivalegeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_privalege.privalege_name
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    private String privalegeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_privalege.privalege_illustration
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    private String privalegeIllustration;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_privalege.CA_Privalege_ID
     *
     * @return the value of ca_privalege.CA_Privalege_ID
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public Integer getCaPrivalegeId() {
        return caPrivalegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_privalege.CA_Privalege_ID
     *
     * @param caPrivalegeId the value for ca_privalege.CA_Privalege_ID
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public void setCaPrivalegeId(Integer caPrivalegeId) {
        this.caPrivalegeId = caPrivalegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_privalege.privalege_name
     *
     * @return the value of ca_privalege.privalege_name
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public String getPrivalegeName() {
        return privalegeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_privalege.privalege_name
     *
     * @param privalegeName the value for ca_privalege.privalege_name
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public void setPrivalegeName(String privalegeName) {
        this.privalegeName = privalegeName == null ? null : privalegeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_privalege.privalege_illustration
     *
     * @return the value of ca_privalege.privalege_illustration
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public String getPrivalegeIllustration() {
        return privalegeIllustration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_privalege.privalege_illustration
     *
     * @param privalegeIllustration the value for ca_privalege.privalege_illustration
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public void setPrivalegeIllustration(String privalegeIllustration) {
        this.privalegeIllustration = privalegeIllustration == null ? null : privalegeIllustration.trim();
    }
}