package com.cafucaa.alumniassociation.model;

public class CaRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_role.CA_Role_ID
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    private Integer caRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_role.role_name
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ca_role.role_illustration
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    private String roleIllustration;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_role.CA_Role_ID
     *
     * @return the value of ca_role.CA_Role_ID
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public Integer getCaRoleId() {
        return caRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_role.CA_Role_ID
     *
     * @param caRoleId the value for ca_role.CA_Role_ID
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public void setCaRoleId(Integer caRoleId) {
        this.caRoleId = caRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_role.role_name
     *
     * @return the value of ca_role.role_name
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_role.role_name
     *
     * @param roleName the value for ca_role.role_name
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ca_role.role_illustration
     *
     * @return the value of ca_role.role_illustration
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public String getRoleIllustration() {
        return roleIllustration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ca_role.role_illustration
     *
     * @param roleIllustration the value for ca_role.role_illustration
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public void setRoleIllustration(String roleIllustration) {
        this.roleIllustration = roleIllustration == null ? null : roleIllustration.trim();
    }
}