package com.cafucaa.alumniassociation.model;

public class RelationshipsActivityClassKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relationships_activity_class.CA_Activity_ID
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    private Integer caActivityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relationships_activity_class.CA_Class_ID
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    private Integer caClassId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relationships_activity_class.CA_Activity_ID
     *
     * @return the value of relationships_activity_class.CA_Activity_ID
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public Integer getCaActivityId() {
        return caActivityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relationships_activity_class.CA_Activity_ID
     *
     * @param caActivityId the value for relationships_activity_class.CA_Activity_ID
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public void setCaActivityId(Integer caActivityId) {
        this.caActivityId = caActivityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relationships_activity_class.CA_Class_ID
     *
     * @return the value of relationships_activity_class.CA_Class_ID
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public Integer getCaClassId() {
        return caClassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relationships_activity_class.CA_Class_ID
     *
     * @param caClassId the value for relationships_activity_class.CA_Class_ID
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public void setCaClassId(Integer caClassId) {
        this.caClassId = caClassId;
    }
}