package com.cafucaa.alumniassociation.model;

public class RelationshipsRolePrivalegeKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relationships_role_privalege.CA_Role_ID
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    private Integer caRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relationships_role_privalege.CA_Privalege_ID
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    private Integer caPrivalegeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relationships_role_privalege.CA_Role_ID
     *
     * @return the value of relationships_role_privalege.CA_Role_ID
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public Integer getCaRoleId() {
        return caRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relationships_role_privalege.CA_Role_ID
     *
     * @param caRoleId the value for relationships_role_privalege.CA_Role_ID
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public void setCaRoleId(Integer caRoleId) {
        this.caRoleId = caRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relationships_role_privalege.CA_Privalege_ID
     *
     * @return the value of relationships_role_privalege.CA_Privalege_ID
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public Integer getCaPrivalegeId() {
        return caPrivalegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relationships_role_privalege.CA_Privalege_ID
     *
     * @param caPrivalegeId the value for relationships_role_privalege.CA_Privalege_ID
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    public void setCaPrivalegeId(Integer caPrivalegeId) {
        this.caPrivalegeId = caPrivalegeId;
    }
}