package com.cafucaa.alumniassociation.mapper;

import com.cafucaa.alumniassociation.model.CaActivity;
import com.cafucaa.alumniassociation.model.CaActivityExample;
import com.cafucaa.alumniassociation.model.CaActivityWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CaActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_activity
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int countByExample(CaActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_activity
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int deleteByExample(CaActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_activity
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int deleteByPrimaryKey(Integer caActivityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_activity
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int insert(CaActivityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_activity
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int insertSelective(CaActivityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_activity
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    List<CaActivityWithBLOBs> selectByExampleWithBLOBs(CaActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_activity
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    List<CaActivity> selectByExample(CaActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_activity
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    CaActivityWithBLOBs selectByPrimaryKey(Integer caActivityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_activity
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int updateByExampleSelective(@Param("record") CaActivityWithBLOBs record, @Param("example") CaActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_activity
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") CaActivityWithBLOBs record, @Param("example") CaActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_activity
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int updateByExample(@Param("record") CaActivity record, @Param("example") CaActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_activity
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int updateByPrimaryKeySelective(CaActivityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_activity
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(CaActivityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_activity
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int updateByPrimaryKey(CaActivity record);
}