package com.cafucaa.alumniassociation.mapper;

import com.cafucaa.alumniassociation.model.CaAlumni;
import com.cafucaa.alumniassociation.model.CaAlumniExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CaAlumniMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_alumni
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int countByExample(CaAlumniExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_alumni
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int deleteByExample(CaAlumniExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_alumni
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int deleteByPrimaryKey(Integer caAlumniId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_alumni
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int insert(CaAlumni record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_alumni
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int insertSelective(CaAlumni record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_alumni
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    List<CaAlumni> selectByExample(CaAlumniExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_alumni
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    CaAlumni selectByPrimaryKey(Integer caAlumniId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_alumni
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int updateByExampleSelective(@Param("record") CaAlumni record, @Param("example") CaAlumniExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_alumni
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int updateByExample(@Param("record") CaAlumni record, @Param("example") CaAlumniExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_alumni
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int updateByPrimaryKeySelective(CaAlumni record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_alumni
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int updateByPrimaryKey(CaAlumni record);
}