package com.cafucaa.alumniassociation.mapper;

import com.cafucaa.alumniassociation.model.CaClass;
import com.cafucaa.alumniassociation.model.CaClassExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CaClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_class
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int countByExample(CaClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_class
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int deleteByExample(CaClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_class
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int deleteByPrimaryKey(Integer caClassId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_class
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int insert(CaClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_class
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int insertSelective(CaClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_class
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    List<CaClass> selectByExample(CaClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_class
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    CaClass selectByPrimaryKey(Integer caClassId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_class
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int updateByExampleSelective(@Param("record") CaClass record, @Param("example") CaClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_class
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int updateByExample(@Param("record") CaClass record, @Param("example") CaClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_class
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int updateByPrimaryKeySelective(CaClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_class
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int updateByPrimaryKey(CaClass record);
}