package com.cafucaa.alumniassociation.mapper;

import com.cafucaa.alumniassociation.model.CaPrivalege;
import com.cafucaa.alumniassociation.model.CaPrivalegeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CaPrivalegeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_privalege
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int countByExample(CaPrivalegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_privalege
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int deleteByExample(CaPrivalegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_privalege
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int deleteByPrimaryKey(Integer caPrivalegeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_privalege
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int insert(CaPrivalege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_privalege
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int insertSelective(CaPrivalege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_privalege
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    List<CaPrivalege> selectByExampleWithBLOBs(CaPrivalegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_privalege
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    List<CaPrivalege> selectByExample(CaPrivalegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_privalege
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    CaPrivalege selectByPrimaryKey(Integer caPrivalegeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_privalege
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int updateByExampleSelective(@Param("record") CaPrivalege record, @Param("example") CaPrivalegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_privalege
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") CaPrivalege record, @Param("example") CaPrivalegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_privalege
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int updateByExample(@Param("record") CaPrivalege record, @Param("example") CaPrivalegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_privalege
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int updateByPrimaryKeySelective(CaPrivalege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_privalege
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(CaPrivalege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_privalege
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int updateByPrimaryKey(CaPrivalege record);
}