package com.cafucaa.alumniassociation.mapper;

import com.cafucaa.alumniassociation.model.CaRole;
import com.cafucaa.alumniassociation.model.CaRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CaRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_role
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int countByExample(CaRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_role
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int deleteByExample(CaRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_role
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int deleteByPrimaryKey(Integer caRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_role
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int insert(CaRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_role
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int insertSelective(CaRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_role
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    List<CaRole> selectByExampleWithBLOBs(CaRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_role
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    List<CaRole> selectByExample(CaRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_role
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    CaRole selectByPrimaryKey(Integer caRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_role
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int updateByExampleSelective(@Param("record") CaRole record, @Param("example") CaRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_role
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") CaRole record, @Param("example") CaRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_role
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int updateByExample(@Param("record") CaRole record, @Param("example") CaRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_role
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int updateByPrimaryKeySelective(CaRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_role
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(CaRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_role
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int updateByPrimaryKey(CaRole record);
}