package com.cafucaa.alumniassociation.mapper;

import com.cafucaa.alumniassociation.model.RelationshipsActivityClassExample;
import com.cafucaa.alumniassociation.model.RelationshipsActivityClassKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RelationshipsActivityClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationships_activity_class
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int countByExample(RelationshipsActivityClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationships_activity_class
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int deleteByExample(RelationshipsActivityClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationships_activity_class
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int deleteByPrimaryKey(RelationshipsActivityClassKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationships_activity_class
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int insert(RelationshipsActivityClassKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationships_activity_class
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int insertSelective(RelationshipsActivityClassKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationships_activity_class
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    List<RelationshipsActivityClassKey> selectByExample(RelationshipsActivityClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationships_activity_class
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int updateByExampleSelective(@Param("record") RelationshipsActivityClassKey record, @Param("example") RelationshipsActivityClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationships_activity_class
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int updateByExample(@Param("record") RelationshipsActivityClassKey record, @Param("example") RelationshipsActivityClassExample example);
}