package com.cafucaa.alumniassociation.mapper;

import com.cafucaa.alumniassociation.model.RelationshipsRolePrivalegeExample;
import com.cafucaa.alumniassociation.model.RelationshipsRolePrivalegeKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RelationshipsRolePrivalegeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationships_role_privalege
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int countByExample(RelationshipsRolePrivalegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationships_role_privalege
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int deleteByExample(RelationshipsRolePrivalegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationships_role_privalege
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int deleteByPrimaryKey(RelationshipsRolePrivalegeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationships_role_privalege
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int insert(RelationshipsRolePrivalegeKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationships_role_privalege
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int insertSelective(RelationshipsRolePrivalegeKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationships_role_privalege
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    List<RelationshipsRolePrivalegeKey> selectByExample(RelationshipsRolePrivalegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationships_role_privalege
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int updateByExampleSelective(@Param("record") RelationshipsRolePrivalegeKey record, @Param("example") RelationshipsRolePrivalegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationships_role_privalege
     *
     * @mbggenerated Sat Jun 01 23:57:31 CST 2019
     */
    int updateByExample(@Param("record") RelationshipsRolePrivalegeKey record, @Param("example") RelationshipsRolePrivalegeExample example);
}